### ISSUE TITLE
The term 'Get-o365DynamicDistributionGroup' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by smtp25gmailcom** [timmcmic/DLConversionV2#100]
It can't find this command 'Get-o365DynamicDistributionGroup' and it also fails for get-o365outboundconnector

[12/21/2022 12:29:23 AM] - Starting collection of dynamic distribution groups.
invoke-command : The term 'Get-o365DynamicDistributionGroup' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.9.4\Get-O365GroupDependency.ps1:144 char:34
+ ...             $functionTest += invoke-command -scriptBlock $scriptBlock
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-o365DynamicDistributionGroup:String) [Invoke-Command], CommandNotFo

**Comment by smtp25gmailcom** [comment]
test-outboundConnector : The term 'get-o365OutboundConnector' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.9.4\DLConversionV2.psm1:2187 char:9
+         test-outboundConnector -overrideCentralizedMailTransportEnabl ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-o365OutboundConnector:String) [Test-OutboundConnector], CommandNotF 
   oundException
    + FullyQualifiedErrorId : CommandNotFoundException,Test-OutboundConnector

**Comment by smtp25gmailcom** [comment]
ok - I can see why I get this error.  For those finding this
O365 is the prefix added to commands so they are differentiated from the onpremise cmds, this prefix is specified when the module connects to EXO.
When I manually connect to EXO those commands don't exist for me either.  I must be having brain fade because I can't see why.  I have exchange admin role active and global just for good measure

**Comment by timmcmic** [comment]
If you’re having to run connect-ExchangeOnline first something else is wrong.  Make sure the account your using is not implementing mfa or use certificate auth.  The script should be able to establish the connection non-interactively,

Generally when I see this someone has to have an interactive logon first - so they leverage the ability that the new commands do not clobber existing commands on import.

Tim


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________
