### ISSUE TITLE
unbale to run start-collectOnPremSendAs

### ISSUE THREAD

**Issue by lsborroto12** [timmcmic/DLConversionV2#115]
I run:
Install-Module dlconversionV2
Import-Module dlconversionV2
import-module exchangeonlinemanagement
update-module DLCONVERSIONV2
update-module PSLogging
SET-EXECUTIONPOLICY UNRESTRICTED
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
Error:
Creating the powershell to server that requires import.
WARNING: Your connection has been redirected to the following URI: "https://exc.ftc365.club/PowerShell-LiveID?PSVersion=5.1.17763.2867 "
New-PSSession : [exc.ftc365.club] Connecting to remote server exc.ftc365.club failed with the following error message : The WinRM client sent a request to an HTTP 
server and got a response saying the requested HTTP URL was not available. This is usually returned by a HTTP server that does not support the WS-Management protocol. 
For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.9.6.3\New-PowershellSession.ps1:110 char:34
+ ... iontoimport=New-PSSession -ConfigurationName $configurationName -Conn ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : URLNotAvailable,PSSessionOpenFailed

**Comment by timmcmic** [comment]
Can you send me the full log please?

From: lsborroto12 ***@***.***>
Sent: Thursday, February 9, 2023 1:02 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] unbale to run start-collectOnPremSendAs (Issue #115)


I run:
Install-Module dlconversionV2
Import-Module dlconversionV2
import-module exchangeonlinemanagement
update-module DLCONVERSIONV2
update-module PSLogging
SET-EXECUTIONPOLICY UNRESTRICTED
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
Error:
Creating the powershell to server that requires import.
WARNING: Your connection has been redirected to the following URI: "https://exc.ftc365.club/PowerShell-LiveID?PSVersion=5.1.17763.2867<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fexc.ftc365.club%2FPowerShell-LiveID%3FPSVersion%3D5.1.17763.2867&data=05%7C01%7Ctimmcmic%40microsoft.com%7C8fa344495a6045f7682d08db0ac7c8d9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638115625406647847%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vbgv%2FAPxarl6%2FLFj5X2IXSu%2Bb%2FiHoAJKYgMETEtb5i4%3D&reserved=0> "
New-PSSession : [exc.ftc365.club] Connecting to remote server exc.ftc365.club failed with the following error message : The WinRM client sent a request to an HTTP
server and got a response saying the requested HTTP URL was not available. This is usually returned by a HTTP server that does not support the WS-Management protocol.
For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.9.6.3\New-PowershellSession.ps1:110 char:34

  *   ... iontoimport=New-PSSession -ConfigurationName $configurationName -Conn ...

*                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*

     *   CategoryInfo : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
     *   FullyQualifiedErrorId : URLNotAvailable,PSSessionOpenFailed

-

**Comment by lsborroto12** [comment]
[OnPremSendAsPermissions.log](https://github.com/timmcmic/DLConversionV2/files/10700499/OnPremSendAsPermissions.log)


I added the logs, thankss

**Comment by timmcmic** [comment]
So based on your previous email it appears that when you're specifying the on premises exchange server information you're somehow being redirected to a powershell live directory somewhere else - that does not match much sense.

Try this - for the exchange sever name use the FQDN of an internal server name and set the exchange authentication method to Kerberos.

Tim

**Comment by lsborroto12** [comment]
thanksss, it is collecting now.

**Comment by timmcmic** [comment]
Something is definitely up with that redirect URL - my guess is that someone has taken you're namespace and pointed it to office 365 for that.

Tim

**Comment by lsborroto12** [comment]
THanks for the response,
