### ISSUE TITLE
Error: Address somename@ could not be added to new cloud distribution group.  Manual addition required.

### ISSUE THREAD

**Issue by TPok1707** [timmcmic/DLConversionV2#125]
I just upgraded to version 2.9.6.6 and now I get the same error message for all migration jobs. This looks to me like some address parsing bug.

Anonymized Log snipped:
```
[23.02.2023 10:48:46] - A hybrid remote routing address was not present.  Adding hybrid remote routing address.
[23.02.2023 10:48:46] - Calculated hybrid remote routing address = some.name@
[23.02.2023 10:48:46] - Determine if the calcualted routing address is already in use.
[23.02.2023 10:48:46] - Calculated hybrid remote routing address is not present - continue.
[23.02.2023 10:48:46] - Error processing address: some.name@
Write-ErrorMessage : Cannot process argument transformation on parameter 'EmailAddresses'. Cannot convert value 
"System.Collections.Generic.Dictionary`2[System.String,System.Object]" to type 
"Microsoft.Exchange.Data.ProxyAddressCollection". Error: "The address 'some.name@' is invalid: The address 
'some.name@' isn't a valid Unified Messaging address, so a prefix must be specified."
At C:\Users\s.fietzek\AppData\Local\Temp\tmpEXO_yeotnggm.l51\tmpEXO_yeotnggm.l51.psm1:1101 char:13
+             Write-ErrorMessage $ErrorObject
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-DistributionGroup], ParameterTransformationException
    + FullyQualifiedErrorId : [Server=DU0PR08MB7762,RequestId=e65f39dd-b4c2-c279-15b0-d3d60a6f680d,TimeStamp=Thu, 23 F 
   eb 2023 09:48:46 GMT],Write-ErrorMessage
 


Name                      : Some Name
Alias                     : some.name
PrimarySMTPAddressorUPN   : some.name@company.com
ExternalDirectoryObjectID : 3eea8f1b-7746-4861-92bf-1a86b036e574
ErrorMessageDetail        : Cannot process argument transformation on parameter 'EmailAddresses'. Cannot convert value 
                            "System.Collections.Generic.Dictionary`2[System.String,System.Object]" to type 
                            "Microsoft.Exchange.Data.ProxyAddressCollection". Error: "The address 'some.name@' is 
                            invalid: The address 'some.name@' isn't a valid Unified Messaging address, so a prefix 
                            must be specified."
Attribute                 : Cloud Proxy Addresses
ErrorMessage              : Address some.name@ could not be added to new cloud distribution group.  Manual addition 
                            required.



[23.02.2023 10:48:46] - Remove the SMTP Address added by creating the temporary DL.
[23.02.2023 10:48:46] - Removing: 20230223T10435929161801342289@company.onmicrosoft.com
[23.02.2023 10:48:46] - END SET-Office365DLMV
```

I can provide a full log directly but not in public.

Looking at the migrated distribution list, everything looks fine to me despite the error message.

**Comment by timmcmic** [comment]
Thank you for the snippet - I'm not sure why this is randomly failing when it's not failing in test cases.  I've reproing both success and failure.

I changed the logic for calculating the routing domain to account for a customized domain.  The variable for the customer domain was set to NULL and there is an IF statement that triggeres pulling the onmicrosoft.com domain.  This is skipped if the administrator specifies this.  For whatever reason this is working at times and not.

I changed the string initialization to just be a blank string "" and the if statement to test for this.  I'm now 100% in the stress tests.

Version .7 will go live here shortly that has this fixed.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: TPok1707 ***@***.***>
Sent: Thursday, February 23, 2023 5:53 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Error: Address somename@ could not be added to new cloud distribution group. Manual addition required. (Issue #125)


I just upgraded to version 2.9.6.6 and now I get the same error message for all migration jobs. This looks to me like some address parsing bug.

Anonymized Log snipped:

[23.02.2023 10:48:46] - A hybrid remote routing address was not present.  Adding hybrid remote routing address.

[23.02.2023 10:48:46] - Calculated hybrid remote routing address = some.name@

[23.02.2023 10:48:46] - Determine if the calcualted routing address is already in use.

[23.02.2023 10:48:46] - Calculated hybrid remote routing address is not present - continue.

[23.02.2023 10:48:46] - Error processing address: some.name@

Write-ErrorMessage : Cannot process argument transformation on parameter 'EmailAddresses'. Cannot convert value

"System.Collections.Generic.Dictionary`2[System.String,System.Object]" to type

"Microsoft.Exchange.Data.ProxyAddressCollection". Error: "The address 'some.name@' is invalid: The address

'some.name@' isn't a valid Unified Messaging address, so a prefix must be specified."

At C:\Users\s.fietzek\AppData\Local\Temp\tmpEXO_yeotnggm.l51\tmpEXO_yeotnggm.l51.psm1:1101 char:13

+             Write-ErrorMessage $ErrorObject

+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [Set-DistributionGroup], ParameterTransformationException

    + FullyQualifiedErrorId : [Server=DU0PR08MB7762,RequestId=e65f39dd-b4c2-c279-15b0-d3d60a6f680d,TimeStamp=Thu, 23 F

   eb 2023 09:48:46 GMT],Write-ErrorMessage







Name                      : Some Name

Alias                     : some.name

PrimarySMTPAddressorUPN   : ***@***.******@***.***>

ExternalDirectoryObjectID : 3eea8f1b-7746-4861-92bf-1a86b036e574

ErrorMessageDetail        : Cannot process argument transformation on parameter 'EmailAddresses'. Cannot convert value

                            "System.Collections.Generic.Dictionary`2[System.String,System.Object]" to type

                            "Microsoft.Exchange.Data.ProxyAddressCollection". Error: "The address 'some.name@' is

                            invalid: The address 'some.name@' isn't a valid Unified Messaging address, so a prefix

                            must be specified."

Attribute                 : Cloud Proxy Addresses

ErrorMessage              : Address some.name@ could not be added to new cloud distribution group.  Manual addition

                            required.







[23.02.2023 10:48:46] - Remove the SMTP Address added by creating the temporary DL.

[23.02.2023 10:48:46] - Removing: ***@***.******@***.***>

[23.02.2023 10:48:46] - END SET-Office365DLMV

I can provide a full log directly but not in public.

Looking at the migrated distribution list, everything looks fine to me despite the error message.

-

**Comment by timmcmic** [comment]
Confirming you should now see this resolved?

**Comment by smtp25gmailcom** [comment]
I got this to too, and it was Azure AD guests, I had to add them manually.

**Comment by timmcmic** [comment]
Azure AD guest accounts cannot be members of distribution lists unless it is a guest account synced from on premise.

Could you by chance provide logs or more specifics?

This issue was fixed already in the other case.

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================
