### ISSUE TITLE
Error in Test-OutboundConnector

### ISSUE THREAD

**Issue by githubths** [timmcmic/DLConversionV2#131]
Script : Test-OutboundConnector.ps1

The Error are Present by the Main Function : Test-PreMigration
IF the Error is wanted then the function must have a optional Paramter OverrideCentralizedMailTransportEnabled for checking if the DL can by migrated.

Out-logfile function hase no parameter -isError 

Line : 54
out-logfile -string "***WARNING***" -isError:$true

Please Replace with
out-logfile -string "***WARNING***"

**Comment by timmcmic** [comment]
I'm not sure what you are asking for here.

Line 54 is valid as far as I can tell.  If any connector is found with route enabled the this function should bail.

out-logfile -string "***WARNING***" -isError:$true

Out-logfile does have a -isError.

From out-logfile

            [Parameter(Mandatory = $false)]
            [boolean]$isError=$FALSE,

Feel free to clarify if i'm not understanding.
