### ISSUE TITLE
Error When Running Start-MultipleMachineDistributionListMigration Command - Unable to set the ACL on the folder for the active directory credential.

### ISSUE THREAD

**Issue by write2tsm** [timmcmic/DLConversionV2#142]
Hi Tim

I'm seeing the below error while running the Start-MultipleMachineDistributionListMigration command:

Start-MultipleMachineDistributionListMigration -groupSMTPAddresses $groups -globalCatalogServer <GCServer> -activeDirectoryCredential $credentials -aadconnectServer <AADConnectServer> -aadConnectCredential $credentials -aadConnectAuthenticationMethod Kerberos -exchangeServer <ExchServer> -exchangeCredential $credentials -exchangeAuthenticationMethod Kerberos -exchangeOnlineCredential $credentials -logFolderPath C:\DLConversion -remoteDriveLetter S -serverNames $machines -dnNoSyncOU "<ADDS OU>

[19/07/2023 3:18:48 PM] - Testing server for presence of DLConversion V2 <ControllerMachine>
[19/07/2023 3:18:48 PM] - Skipping test - this is the machine running the controller.
[19/07/2023 3:18:51 PM] - Creating DLConversionV2 to share to support centralized logging.
[19/07/2023 3:18:53 PM] - Setting the ACL on the folder for full control to the active directory credential and enabling inheritance.

    Directory: C:\

Path         Owner                  Access                                                                                                          
----         -----                  ------                                                                                                          
DLConversion BUILTIN\Admin NT AUTHORITY\SYSTEM Allow  FullControl...                                                                       

<DomainAdminAccount>
FullControl
ContainerInherit, ObjectInherit
None
Allow

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : <DomainAdminAccount>
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

    Directory: C:\

Path         Owner                  Access                                                                                                          
----         -----                  ------                                                                                                          
DLConversion BUILTIN\Admin <Domain\DomainAdminAccount> Allow  FullControl...                                                                     

[19/07/2023 3:18:53 PM] - Setting the ACL on the folder for full control for machine accounts to the active directory credential and enabling inheritance.
[19/07/2023 3:18:54 PM] - **Unable to set the ACL on the folder for the active directory credential.
get-adComputer : The server has rejected the client credentials.**
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.9.8.13\start-MultipleMachineDistributionListMigration.ps1:663 char:34
+ ... countName = get-adComputer -identity $forServerName[0] -server $globa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (<ControllerMAchine>:ADComputer) [Get-ADComputer], AuthenticationException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.Security.Authentication.AuthenticationException,Microsoft.ActiveDirectory.Management.Com 
   mands.GetADComputer
 
[19/07/2023 3:18:54 PM] - ********************************************************************************
[19/07/2023 3:18:54 PM] - BEGIN disable-allPowerShellSessions
[19/07/2023 3:18:54 PM] - ********************************************************************************
[19/07/2023 3:18:54 PM] - Gathering all PS Sessions
[19/07/2023 3:18:54 PM] - Disconnecting Exchange Online Session
[19/07/2023 3:18:54 PM] - Removing other non-Exchange Online powershell sessions.
2
[19/07/2023 3:18:54 PM] - WinRM2
[19/07/2023 3:18:54 PM] - <ExchServer>
[19/07/2023 3:18:55 PM] - ***IT MAY BE NECESSARY TO EXIT THIS POWERSHELL WINDOW AND REOPEN TO RESTART FROM A FAILED MIGRATION***
[19/07/2023 3:18:55 PM] - END disable-allPowerShellSessions
[19/07/2023 3:18:55 PM] - ********************************************************************************
[19/07/2023 3:18:55 PM] - ********************************************************************************

ParameterName       Bound  ParameterValue
-------------       -----  --------------
isSuccess            True           False
logFolderPath        True C:\DLConversion
isHealthCheck       False           False
Verbose             False                
Debug               False                
ErrorAction         False                
WarningAction       False                
InformationAction   False                
ErrorVariable       False                
WarningVariable     False                
InformationVariable False                
OutVariable         False                
OutBuffer           False                
PipelineVariable    False                

[19/07/2023 3:18:55 PM] - ********************************************************************************
[19/07/2023 3:18:55 PM] - Archiving files associated with run.
[19/07/2023 3:18:55 PM] - Split string for group name.
C:
DLConversion

What am I missing here?

Thanks

**Comment by write2tsm** [comment]
I'm able to run the get-adComputer command successfully (with Shortname not FQDN - not sure if that matters):

<img width="909" alt="get-adComputer" src="https://github.com/timmcmic/DLConversionV2/assets/26711222/4e99b915-99ab-477b-b34c-3dcfe1ba3495">

The account specified is a Domain Admin.

**Comment by timmcmic** [comment]
Do you get the credential error with fqdn?


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________

**Comment by write2tsm** [comment]
It says "**Cannot find an object with Ideneity <FQDN>**",as is covered in the previous screenshot (first attempt was with FQDN).

Thanks

**Comment by timmcmic** [comment]
Sorry I did not see a screen shot attached to the previous.  I'll need to take a look.  If memory serves the call is by FQDN in the code.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by write2tsm** [comment]
Hi Tim

Quick update on this one....the issue somehow disappeared when I ran the same command again this morning. Still unsure why, but seems like some intermittent issue.


Thanks

**Comment by timmcmic** [comment]
Multiple machine migrations can be somewhat fragile - they work great when they work but not so much when they do not.  Generally most stick to multi single machines.


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________
