### ISSUE TITLE
Start-MultipleDistributionListMigration is failing

### ISSUE THREAD

**Issue by lsborroto** [timmcmic/DLConversionV2#152]
I am running the Start-MultipleDistributionListMigration, btu it stills failing.
[DLBatch1.log](https://github.com/timmcmic/DLConversionV2/files/13352209/DLBatch1.log)
[DLBatch2.log](https://github.com/timmcmic/DLConversionV2/files/13352213/DLBatch2.log)

**Comment by timmcmic** [comment]
The graph application that you're using lacks sufficient scopes to do the work required.

I would manually connect with graph and the cert information - specify the scopes read.users.all and read.groups.all and consent.

Tim

From: lsborroto ***@***.***>
Sent: Tuesday, November 14, 2023 12:11 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Start-MultipleDistributionListMigration is failing (Issue #152)


I am running the Start-MultipleDistributionListMigration, btu it stills failing.
DLBatch1.log<https://github.com/timmcmic/DLConversionV2/files/13352209/DLBatch1.log>
DLBatch2.log<https://github.com/timmcmic/DLConversionV2/files/13352213/DLBatch2.log>

-

**Comment by lsborroto** [comment]
I run get-MgContext and the Scopes are empty.

**Comment by timmcmic** [comment]
So if you make the connection manually using this same information - and specifying the scopes required - you are not prompted to consent?

**Comment by lsborroto** [comment]
Sorry I don't known how to make it? I used:
Connect-MgGraph -TenantId "tenant" -AppId "app" -CertificateThumbprint "cert"

**Comment by timmcmic** [comment]
Add -scopes {Read.user.all,read.groups.all}

**Comment by lsborroto** [comment]
Connect-MgGraph -TenantId "tenant" -AppId "app" -CertificateThumbprint "cert" -scopes {Read.user.all,read.groups.all}
At line:1 char:200
+ ... F5649C86F66BE7C6FA58DDA2742F0EF5A10B" -scopes {Read.user.all,read.gro ...
+                                                                 ~
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument
