### ISSUE TITLE
Issues with migration failing in slow replicated networks

### ISSUE THREAD

**Issue by JerBar** [timmcmic/DLConversionV2#153]
I think I am having an issue where current network replication is slower than most enviroments.

I'm seeing odd behavior, with the module getting setting the email address in the cloud.
It seems that it is changing it to the correct email addresses, then changing it back to the the temp email address and then failing.
I can see the email address changes in the Entra ID (Azure AD) Audit Logs on the group.

Start-distributionListMigration -msGraphTenantID $msGraphTenantID -msGraphCertificateThumbprint $msGraphCertificateThumbprint -msGraphApplicationID $msGraphApplicationID -globalCatalogServer $GCServer -activeDirectoryCredential $gcCred -groupSMTPAddress 'TestDL82@clientdomain.com' -AADConnectServer $AADServer -aadConnectCredential $adConnectCred -aadConnectAuthenticationMethod Kerberos -logFolderPath c:\temp -dnNoSyncOU $DNSyncOU -customroutingdomain $CustomRoutingDomain -exchangeserver $exchangeserver -exchangecredential $exchangeCred -exchangeAuthenticationMethod Kerberos -exchangeOnlineCertificateThumbPrint $msGraphCertificateThumbprint  -exchangeOnlineOrganizationName $ExchangeOnlineOrg  -exchangeOnlineAppID $msGraphApplicationID

I've tried with and w/o the -customroutingdomain and it seems to behave the same.

**Comment by timmcmic** [comment]
Submit the full log to ***@***.******@***.***> dlconversionv2 at service dot Microsoft dot com

Tim

From: JerBar ***@***.***>
Sent: Wednesday, December 13, 2023 9:44 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Issues with migration failing in slow replicated networks (Issue #153)


I think I am having an issue where current network replication is slower than most enviroments.

I'm seeing odd behavior, with the module getting setting the email address in the cloud.
It seems that it is changing it to the correct email addresses, then changing it back to the the temp email address and then failing.
I can see the email address changes in the Entra ID (Azure AD) Audit Logs on the group.

Start-distributionListMigration -msGraphTenantID $msGraphTenantID -msGraphCertificateThumbprint $msGraphCertificateThumbprint -msGraphApplicationID $msGraphApplicationID -globalCatalogServer $GCServer -activeDirectoryCredential $gcCred -groupSMTPAddress ***@***.******@***.***>' -AADConnectServer $AADServer -aadConnectCredential $adConnectCred -aadConnectAuthenticationMethod Kerberos -logFolderPath c:\temp -dnNoSyncOU $DNSyncOU -customroutingdomain $CustomRoutingDomain -exchangeserver $exchangeserver -exchangecredential $exchangeCred -exchangeAuthenticationMethod Kerberos -exchangeOnlineCertificateThumbPrint $msGraphCertificateThumbprint -exchangeOnlineOrganizationName $ExchangeOnlineOrg -exchangeOnlineAppID $msGraphApplicationID

I've tried with and w/o the -customroutingdomain and it seems to behave the same.

-
