### ISSUE TITLE
Graph Permissions

### ISSUE THREAD

**Issue by rich872** [timmcmic/DLConversionV2#175]
Where can I find exactly what graph API permissions are needed?

**Comment by timmcmic** [comment]
Show-quickStartGuide and follow the instructions.

From: rich872 ***@***.***>
Sent: Tuesday, June 4, 2024 2:15 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Graph Permissions (Issue #175)


Where can I find exactly what graph API permissions are needed?

-

**Comment by rich872** [comment]
Thank you.   BTW - I just got this set up and working in our lab.  Major kudos for this.  The amount of work that has gone into getting pretty much every facet of a DL migration accounted for, is beyond impressive.   We have over 5k DLs to migrate and this will be such a lifesaver.

**Comment by timmcmic** [comment]
Fantastic!
