### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by gkantarovich-verint** [timmcmic/DLConversionV2#178]
Getting this error when trying to import module DLConversionV2

**Comment by timmcmic** [comment]
Uninstall the exchange shell and install version 3.4 - see previous issue.


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________
From: gkantarovich-verint ***@***.***>
Sent: Monday, June 10, 2024 2:13 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' (Issue #178)


Getting this error when trying to import module DLConversionV2

**Comment by gkantarovich-verint** [comment]
That worked. Thank you!
