### ISSUE TITLE
ERROR:  One permissions method to connect to Exchange Online must be specified.

### ISSUE THREAD

**Issue by gkantarovich-verint** [timmcmic/DLConversionV2#179]
Command used
Start-MultipleDistributionListMigration -globalCatalogServer $GC -activeDirectoryCredential $adcred -groupSMTPAddress $groups -logFolderPath c:\temp -exchangeServer $Exch -exchangeCredential $adcred -msGraphTenantID $tenantID -dnNoSyncOU $OU -aadConnectServer $ADC -aadConnectCredential $adcred -activeDirectoryAuthenticationMethod negotiate -msGraphApplicationID $appID -msGraphCertificateThumbprint $Thprint

**Comment by timmcmic** [comment]
You've not provided any exchange online connectivity information.

Run show-quickStartGuide to see all the pre-reqs.

Run show-sampleMigrationScript for sampel commands.

Tim


From: gkantarovich-verint ***@***.***>
Sent: Thursday, June 20, 2024 4:32 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] ERROR: One permissions method to connect to Exchange Online must be specified. (Issue #179)


Command used
Start-MultipleDistributionListMigration -globalCatalogServer $GC -activeDirectoryCredential $adcred -groupSMTPAddress $groups -logFolderPath c:\temp -exchangeServer $Exch -exchangeCredential $adcred -msGraphTenantID $tenantID -dnNoSyncOU $OU -aadConnectServer $ADC -aadConnectCredential $adcred -activeDirectoryAuthenticationMethod negotiate -msGraphApplicationID $appID -msGraphCertificateThumbprint $Thprint

-

**Comment by gkantarovich-verint** [comment]
Ah, sorry.  I didn't think it was required. I didn't have to provide exchange online connectivity information for single DL migrations.





________________________________

**Comment by timmcmic** [comment]
I’m not sure how you’d get any migration to work without specifying exchange online connection unless you were using interactive authentication.


==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday – Wednesday 08:00 – 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

________________________________

**Comment by gkantarovich-verint** [comment]
Right, I was using interactive authentication.
Thank you very much for your help and all the work you've done.




________________________________
