### ISSUE TITLE
Job will not complete

### ISSUE THREAD

**Issue by rich872** [timmcmic/DLConversionV2#180]
I'm testing out migrating multiple DLs.  I added 10 DLs to the batch.txt file and it seems to be stuck on a certain job.  It created 5 jobs (expected) and all finished except for Job ID: 9.  Its just been in  a running state now for several hours.  All the other jobs finished quickly.  These DLs are test DLs all the exact same execpt name and email address, all have 10 members not much too them.   Cant find much in logs to determine where its stuck at or on.  Its just in this sleeping for 30 seconds waiting for job to finish loop.  Any advice on how to troubleshoot?

**Comment by timmcmic** [comment]
When you look in the thread folders - do you see any DLConversion folders that would indicate an active migration thread is in progress?

From: rich872 ***@***.***>
Sent: Tuesday, June 25, 2024 8:03 AM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Job will not complete (Issue #180)


I'm testing out migrating multiple DLs. I added 10 DLs to the batch.txt file and it seems to be stuck on a certain job. It created 5 jobs (expected) and all finished except for Job ID: 9. Its just been in a running state now for several hours. All the other jobs finished quickly. These DLs are test DLs all the exact same execpt name and email address, all have 10 members not much too them. Cant find much in logs to determine where its stuck at or on. Its just in this sleeping for 30 seconds waiting for job to finish loop. Any advice on how to troubleshoot?

-

**Comment by rich872** [comment]
Ok so, I do see the five thread folders, and see failures for 5 of the 10 DLs I was trying to migrate, but do not see any indication of an active migration currently in progress.

**Comment by timmcmic** [comment]
Ok - if that's the case and the controller is still running go ahead and CTRL-C the controller.

Then run get-job.  If you see the job in progress run receive-job and pull what it's doing.  If there are no active thread folders there should be no active jobs.

Tim

**Comment by rich872** [comment]
Got it.  Appreciate the quick response as always.
