### ISSUE TITLE
2.4.9.3 - The specified directory service attribute or value does not exist : msExchGroupExternalMemberCount

### ISSUE THREAD

**Issue by dimmthewitted** [timmcmic/DLConversionV2#30]
The specified directory service attribute or value does not exist 
Parameter name msExchGroupExternalMemberCount
At c:\Program Files\WindowsPowerShell\Modules\DLCONVERSIONv2\2.4.9.3\DLConversionV2.psml:3861 char:21
out-Logfile -string $_ -isError:$TRUE

![image](https://user-images.githubusercontent.com/13334181/147609110-b1232314-ee9a-459e-a0b0-163509e4530b.png)

**Comment by timmcmic** [comment]
What version of Exchange do you have on premises.

Can you do an LDP dump of the group you are trying to migrate?  On a domain controller -> start -> run -> LDP.

Connection - connect

Connection - bind.

View - > tree -> OK.

Navigate the directory structure to the group.

Connection -> New

Double click on the group and copy all of the information on the right.

You can also send me the XML file of the group backup from the audit logs.

Timmcmic at Microsoft dot com

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: dimmthewitted ***@***.***>
Sent: Tuesday, December 28, 2021 4:41 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] 2.4.9.3 - The specified directory service attribute or value does not exist : msExchGroupExternalMemberCount (Issue #30)


The specified directory service attribute or value does not exist
Parameter name msExchGroupExternalMemberCount
At c:\Program Files\WindowsPowerShell\Modules\DLCONVERSIONv2\2.4.9.3\DLConversionV2.psml:3861 char:21
out-Logfile -string $_ -isError:$TRUE

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13334181%2F147609110-b1232314-ee9a-459e-a0b0-163509e4530b.png&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc3d66f1b8cff457bc85f08d9ca4ac82b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763244819450191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=C1mDNFArXyEgcIG8EUjFFdWTS7HU0xI7Y%2BcAihVZt8E%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftimmcmic%2FDLConversionV2%2Fissues%2F30&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc3d66f1b8cff457bc85f08d9ca4ac82b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763244819450191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SXXtNIX5QWPiiH7AE%2BnafQoUwTmVx%2B%2BCFLHPoNLGO7w%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKGTN6P657SWKDU52DWBFPDUTIVH5ANCNFSM5K42IPTA&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc3d66f1b8cff457bc85f08d9ca4ac82b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763244819450191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kfRxBv1yCiAK2TY6WPoOYcpZ7sZEHVTx2PicfLdI3YM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc3d66f1b8cff457bc85f08d9ca4ac82b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763244819450191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZYmCYR8dJo79MAGM5YZOPpaT5gbMiMp2AFyrPXMYyGQ%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc3d66f1b8cff457bc85f08d9ca4ac82b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763244819450191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=t7y0FrwyaPmYLlQhYfzd%2BJ%2F0tgV4kFL%2BXqNILBWEe%2B4%3D&reserved=0>.

**Comment by danoldenkamp** [comment]
This error is preceded by:
cannot find a provider with the name 'Microsoft.ActiveDirectory.Management.dll
Category Info: Object not found.  [Get-Acl]

![image](https://user-images.githubusercontent.com/96799655/147680923-ddb69218-88f9-456a-a14d-df011e2a1c38.png)

Will send you the Log directly.

**Comment by timmcmic** [comment]
What version of Windows are you using?

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================
