### ISSUE TITLE
Error importing the send as permissions from collect function.

### ISSUE THREAD

**Issue by danoldenkamp** [timmcmic/DLConversionV2#31]
Error importing the send as permissions from collect function.
Could not find a part of the path c:\Scripts\AuditData\onPremRecipientsSendAs.xml
Looks like the shell session is having trouble writing the XML files for useCollected true arguments.

Note:  Powershell ISE run as admin from c:\Scripts
c:\Scripts\AuditData was created by script and user all users have full permissions. 
Looks like XML is not being written but errors out when attempting to read.

![image](https://user-images.githubusercontent.com/96799655/147612802-b250acb7-2825-4cf9-b71f-d0cc17d2cbdc.png)

**Comment by timmcmic** [comment]
Can you post the full command for me that you're running and I'll retest to ensure there's not a regression.

Also does this reproduce outside of ISE?

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: danoldenkamp ***@***.***>
Sent: Tuesday, December 28, 2021 5:51 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Error importing the send as permissions from collect function. (Issue #31)


Error importing the send as permissions from collect function.
Could not find a part of the path c:\Scripts\AuditData\onPremRecipientsSendAs.xml
Looks like the shell session is having trouble writing the XML files for useCollected true arguments.

Note: Powershell ISE run as admin from c:\Scripts
c:\Scripts\AuditData was created by script and user all users have full permissions.
Looks like XML is not being written but errors out when attempting to read.

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F96799655%2F147612802-b250acb7-2825-4cf9-b71f-d0cc17d2cbdc.png&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc6ec858b23d146d90f3808d9ca547330%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763286352185641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sN82dDRZswrk1JjWcdVQFifBmIGZCce%2FMFX04A4gQB4%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftimmcmic%2FDLConversionV2%2Fissues%2F31&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc6ec858b23d146d90f3808d9ca547330%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763286352185641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2w%2FtIgzarsrsejs4dh9i3%2ByeW6QVH3%2FxaEoDfF%2BlTic%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKGTN6NGXRAYRSMZ4N7LYUTUTI5LNANCNFSM5K44WK2Q&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc6ec858b23d146d90f3808d9ca547330%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763286352185641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c%2FalLSxsbAQfUBQmQUpopqkBELuBI%2FdHDo7pcxLBVlE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc6ec858b23d146d90f3808d9ca547330%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763286352185641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3wyGLJAuG7iT9Iyot46qcfVxRkSi7GL6xHHLeE7%2BBe8%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctimmcmic%40microsoft.com%7Cc6ec858b23d146d90f3808d9ca547330%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763286352185641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Cq%2Fq8TncsskS02uPz77knfAeG9e450cdoejtLZJYNog%3D&reserved=0>.

**Comment by danoldenkamp** [comment]
Hi Tim, thanks for the response.  It looks like it is able to create the XML files now for the collected permissions.  But new error.  Limited availability on how we can run this.  I believe we had missed installing/importing the PSLogging module.  Will continue on other issue thread.  


anyone reading this in the future, pre-requisites:


SET-EXECUTIONPOLICY UNRESTRICTED
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

import-module exchangeonlinemanagement  
#install-module exchangeonlinemanagement 
#update-module exchangeonlinemanagement

import-module DLCONVERSIONV2            
#install-module DLCONVERSIONV2           
#update-module DLCONVERSIONV2

import-module PSLogging                 
#install-module PSLogging                
#update-module PSLogging

Get-InstalledModule 
#confirm versions.

**Comment by timmcmic** [comment]
PSLogging in not utilized in version 2.0.  If you installed it and fixed something let me know.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by danoldenkamp** [comment]
Hi Tim,

We ran the commandlet from the powershell ISE directly on the domain controller directly , same server as called out in the argument globalCatalogServer.  (Windows server 2016)

we did run the install-module PSLogging prior to running the script in the last attempts.
After installing the PSLogging, I believe, is when the logs started to show the XML.

I will look into the pre-collection functions.

Respectfully,


Dan Oldenkamp
Systems Engineer | Zones, Inc.
Cell:+1 206 883-6228

***@***.******@***.***> | www.zones.com<https://urldefense.proofpoint.com/v2/url?u=https-3A__na01.safelinks.protection.outlook.com_-3Furl-3Dhttp-253A-252F-252Fwww.zones.com-252F-26data-3D02-257C01-257Cdannyflo-2540microsoft.com-257C6687232d45374ceb41af08d5bb422fc8-257C72f988bf86f141af91ab2d7cd011db47-257C1-257C0-257C636620815301592173-26sdata-3D0yZJh2-252F2LKJssZGZ8WFoYTAbRP7pZ-252FS-252Bi-252B8T3PSTdOc-253D-26reserved-3D0&d=DwMFAg&c=bFSfV3JDZVFjkVdrOg1Bnsgwku-x_EGNRi2KNxwvClI&r=L8SEBjHC27hN_3fMJxqm81gRvO72lWkpmRitEmNKbGs&m=xJjEY9oPiZ8jdaCxPbKHeWIWlfBVUwBwJUhaYNuEu_M&s=tTVZK0BA2B1yEfn3-fp9OSZuc9gnnBlS-p_2stMkSGE&e=>

***@***.***<http://zones.com/>
***@***.******@***.***<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_Zones&d=DwMGaQ&c=bFSfV3JDZVFjkVdrOg1Bnsgwku-x_EGNRi2KNxwvClI&r=SPcNnd8VamiKxbecXXbTxKS9dCUwus5MwT6RlPzMNsc&m=52qf4bzxr8aK_2-beWSGsKABTzytLLo-2lXeYI_OIPA&s=7rE77fFMDe0o0vRckA9jQVqco7ggh15HS3Ak56cxgn8&e=> ***@***.*** <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.youtube.com_user_ZonesITSolutions&d=DwMGaQ&c=bFSfV3JDZVFjkVdrOg1Bnsgwku-x_EGNRi2KNxwvClI&r=SPcNnd8VamiKxbecXXbTxKS9dCUwus5MwT6RlPzMNsc&m=52qf4bzxr8aK_2-beWSGsKABTzytLLo-2lXeYI_OIPA&s=6yKLR80cqSLTA9oihaer_0O3Ul-i7R7vwgHo9JqRe2s&e=>  ***@***.*** <http://blog.zones.com/>

**Comment by timmcmic** [comment]
That’s extremely odd - version 2 intentionally removed that.  The pslogging did funky stuff with interpreting pipeline output which made other things difficult.

Admittedly I’ve never run this in a domain co troller directly only on a remote server.  There was an inherent assumption on my part thay wouldn’t be done - and I wonder if that’s where we’re having some issues since the script creates remote powershell sessions to run get-acl which would essentially loop back around to itself.

Would you be able to test on a machine other than a domain controller.

Tim


________________________________
