### ISSUE TITLE
Migrations are failing for distribution lists that do not have full attributes

### ISSUE THREAD

**Issue by dimmthewitted** [timmcmic/DLConversionV2#32]
Our own premise exchange was decommissioned years ago.
We have created on premise DLs through a script.

Our DLs are missing a number of core exchange attributes and the conversion is failing.

Cannot bind parameter 'String' because it is null.

**Comment by timmcmic** [comment]
A group will be provisioned in Exchange Online as a mail enabled group if it has a mail attribute set and one of more msExch* attribute set.   For example, if you set the MAIL field and then set msExchHiddenFromAddressBook to TRUE then you will end up with a distribution list created in Office 365.

The script now allows for migration of these lists - but taking any values not present in the on premises active directory and substituing in the values from the distribution list that exists in Office 365.
