### ISSUE TITLE
The term 'get-o365OutboundConnector' is not recognized

### ISSUE THREAD

**Issue by LT-DB** [timmcmic/DLConversionV2#35]
Having an issue with start-migrationListMigration; however, I believe this is a section used by any of the methods that utilize the centralized mail flow option.

When the code goes to "Test-OutboundConnector" I receive the following messages:

[2/14/2022 6:27:41 AM] - BEGIN Test-OutboundConnectors
[2/14/2022 6:27:41 AM] - ********************************************************************************
PS C:\Windows\system32> TerminatingError(Test-OutboundConnector): "The term 'get-o365OutboundConnector' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
The term 'get-o365OutboundConnector' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[2/14/2022 6:27:41 AM] - Unable to test outbound connectors for centralized mail flow
out-logfile : [2/14/2022 6:27:41 AM] - Unable to test outbound connectors for centralized mail flow
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.5.9\DLConversionV2.psm1:2059 char:9
+         out-logfile -string "Unable to test outbound connectors for c ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Out-LogFile
out-logfile : [2/14/2022 6:27:41 AM] - Unable to test outbound connectors for centralized mail flow
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.5.9\DLConversionV2.psm1:2059 char:9
+         out-logfile -string "Unable to test outbound connectors for c ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Out-LogFile

[2/14/2022 6:27:41 AM] - ********************************************************************************
[2/14/2022 6:27:41 AM] - BEGIN disable-allPowerShellSessions

I am executing

Start-MultipleDistributionListMigration -groupSMTPAddress $groups -globalCatalogServer "DCServer.domain.edu" -activeDirectoryCredential $onpremcred -logFolderPath "e:\temp\DLMigrations2" -aadConnectServer "AADServer.Domain.edu" -aadConnectCredential $onpremcred -exchangeServer "exchangeServer.domain.edu" -exchangeCredential $onpremcred -exchangeOnlineOrganizationName "tenantName.onmicrosoft.com" -exchangeOnlineCertificateThumbPrint "thumbrint" -exchangeOnlineAppID "AppIDNumber"  -useCollectedFullMailboxAccessOnPrem:$FALSE -useCollectedFullMailboxAccessOffice365:$TRUE -useCollectedSendAsOnPrem:$FALSE -useCollectedFolderPermissionsOnPrem:$FALSE -useCollectedFolderPermissionsOffice365:$FALSE -triggerUpgradeToOffice365Group:$FALSE -enableHybridMailflow:$TRUE -dnNoSyncOU "OU=Deactivated Hold,DC=Domain,DC=edu" -exchangeAuthenticationMethod "kerberos" -verbose

**Comment by timmcmic** [comment]
Current investigation status - in this instance certificate based authentication is being utilized.  New code was added in this version tthat checks outbound connectors for centralized mail flow.  This becomes necessary if objects remain on premises.  It appears get-outbound connector is not in the management scope of the application therefore it is failing this check.  Support case opened with exchange online support pending outcome of that.  Recommendations to follow pending outcomes of that.

**Comment by timmcmic** [comment]
No repro.
