### ISSUE TITLE
There are multiple recipients matching identity. Please specify a unique value

### ISSUE THREAD

**Issue by A-J-A** [timmcmic/DLConversionV2#41]
Hi, 
Just been using the script to migrate a Mail-enabled security group, the migration fails with the error ‘There are multiple recipients matching identity "Department of Engineering". Please specify a unique value.’

2 other groups are (not mail-enabled) are being synced already with the same display name.

Any recommendations on a workaround?

**Comment by timmcmic** [comment]
Hello - please download the lastest version.

Code was changed to stop using mailNickname after it was determined that mailNickName does not have a unique constraint.   Now when the DL is created we automatically update the post create configuration - and use the externalDirectoryObjectID for each call from that point forward.

That should eliminate this moving forward.

**Comment by A-J-A** [comment]
Hi, 
I have just updated to v 2.5.14.0 but get this error:

Name                                 DisplayName               GroupType                  PrimarySmtpAddress                     
----                                 -----------               ---------                  ------------------                     
Department of Engineering_7357ca4364 Department of Engineering Universal, SecurityEnabled DepartmentofEngineering@xmail.mmu.ac.uk


Name                                 DisplayName               GroupType                  PrimarySmtpAddress                     
----                                 -----------               ---------                  ------------------                     
Department of Engineering_451d208347 Department of Engineering Universal, SecurityEnabled DepartmentofEngineering@xmail.ac.uk


[18/03/2022 13:35:43] - Group Type Override = None
[18/03/2022 13:35:43] - The group type for evaluation is = -2147483640
[18/03/2022 13:35:43] - A group type override was not specified.  Using group type from on premises.
[18/03/2022 13:35:43] - The group type from on premises is security.
[18/03/2022 13:35:43] - Creating the distribution group in Office 365.
[18/03/2022 13:35:43] - On premises group has a mail nickname specified - using on premsies value.
[18/03/2022 13:35:43] - DepartmentofEngineering
There are multiple recipients matching identity "Department of Engineering". Please specify a unique value.
At C:\Users\admin\AppData\Local\Temp\tmp_nhuyz1u4.f01\tmp_nhuyz1u4.f01.psm1:39124 char:9
+         $steppablePipeline.End()
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-DistributionGroup], TaskException
    + FullyQualifiedErrorId : [Server=VE1P192MB0768,RequestId=93447054-ebf8-4a70-a1aa-b058601d0285,TimeStamp=18/03/2022 13:35:44] [FailureCategory=Cmdlet-TaskException] 256D8A2,Microsoft.Exchange.Managemen 
   t.RecipientTasks.NewDistributionGroup
 
Out-LogFile : There are multiple recipients matching identity "Department of Engineering". Please specify a unique value.
At C:\Users\admin\Documents\WindowsPowerShell\Modules\DLConversionV2\2.5.14.0\New-Office365DL.ps1:135 char:13
+             Out-LogFile -string $_ -isError:$TRUE
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Out-LogFile

**Comment by timmcmic** [comment]
Hi!  Ok thank you for posting this.

So I went through and took some more changes.  The first was to also move the unambiguous DL creation into new DL.  So it looks like new DL, set DL etc all trip up when there's other things that come close to matching across all attributes like name / alias / etc.

So now the code creates a generic blank DL - then later on renames it which eliminates all collisions.  The set operations now use externalDirectoryObjectID - which allows it to reference the exact group that was created.

Can you try this new build 2.5.14.1 and advise?

Tim
