### ISSUE TITLE
Issue when a DL has "Send As" permissions on itself

### ISSUE THREAD

**Issue by Massimo80** [timmcmic/DLConversionV2#49]
When a distribution list has "Send As" permissions granted to itself (using "NT AUTHORITY\SELF"), the conversion process fails to properly analyze this ACE and errors out.

![Permissions](https://user-images.githubusercontent.com/6884635/167109833-8801e96d-3b3c-40f0-b644-1f909f37e474.png)

Attached (anonymized) error log: [Log.txt](https://github.com/timmcmic/DLConversionV2/files/8639138/Log.txt)

Workaround:  remove the permission granted to "NT AUTHORITY\SELF" and assign it explicitly to the group.

Suggested resolution: when a "Send As" ACE refers to "NT AUTHORITY\SELF", map it to the group's own DN.

**Comment by timmcmic** [comment]
You can send as a distribution list that is not a mail security group.  Unfortunately exchange recycles this all the way around.  The send as acl applies to all mail enabled objects for the purposes of send as.  Limiting to one recipient type would not work.

What is the issue you're having?

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by Massimo80** [comment]
> Can you open an issue on git hub.

I already opened it, we are commenting on that :)

>Do you know if the send as ACL actually works in this case?

Yes. They used it on a bunch of groups and have been happily sending as for a while.

Replacing "NT AUTHORITY\SELF" with the actual group name also works (if the group is a security one), and your scripts then are able to handle it correctly; the permission gets correclty applied in Exchange Online after conversion.

So my suggestion is to just handle "NT AUTHORITY\SELF" as an edge case in `Get-NormalizedDN` and map it to the group's own DN.

**Comment by timmcmic** [comment]
I'll work on some testing this weekend.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by timmcmic** [comment]
2.5.19 was just published to the powershell gallery and should have the functionality you're looking for.

I simplied the suggestion.  I get-sendasOnGroup the code enumerates all acls.  It then splits the domain\user into just USER.

Since the DN is passed into the function - the enumeration now tests for SELF and if self is present it subs in the DN instead of searching the AD for the DN.

Then it's normalized as part of the array and returned.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by Massimo80** [comment]
> 2.5.19 was just published to the powershell gallery and should have the functionality you're looking for. I simplied the suggestion. I get-sendasOnGroup the code enumerates all acls. It then splits the domain\user into just USER. Since the DN is passed into the function - the enumeration now tests for SELF and if self is present it subs in the DN instead of searching the AD for the DN. Then it's normalized as part of the array and returned.

Looks great, I'll test it and let you know how it goes.

**Comment by Massimo80** [comment]
This works great.

The permission is handled correctly for security groups, and if the group is a pure distribution one it's already covered by not retaining its send as rights:

```
[07/05/2022 16:43:58] - Retain Office 365 send as set to try - invoke only if group is type security on premsies.
[07/05/2022 16:43:58] - Group is not security on premsies therefore has no send as rights in Office 365.
```
