### ISSUE TITLE
No command proxies have been created

### ISSUE THREAD

**Issue by derekhansell** [timmcmic/DLConversionV2#5]
Hey there!

I'm getting this error attempting to use v2. Log file is attached.

```
[8/11/2021 12:44:59 PM] - Importing powershell session.
Import-PSSession : No command proxies have been created, because all of the requested remote commands would shadow existing local commands.  Use the AllowClobber parameter if you want to 
shadow existing local commands.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.2.0\Import-PowershellSession.ps1:45 char:13
+             Import-PSSession -Session $PowershellSession -ErrorAction ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Import-PSSession], ArgumentException
    + FullyQualifiedErrorId : ErrorNoCommandsImportedBecauseOfSkipping,Microsoft.PowerShell.Commands.ImportPSSessionCommand

```

**Comment by derekhansell** [comment]
OK, got it. I was importing the Exchange on-prem snapin. However, I also get this error when the operation bombs out seemingly for any reason. I have to start a whole new PowerShell ISE window to try again.

**Comment by timmcmic** [comment]
The script automatically exists on error from the session and writes to the session file.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by derekhansell** [comment]
New error after successful creation of DL in Exchange Online:

```
[8/11/2021 1:24:44 PM] - END New-Office365DL
[8/11/2021 1:24:44 PM] - ********************************************************************************
[8/11/2021 1:24:44 PM] - ********************************************************************************
[8/11/2021 1:24:44 PM] - BEGIN GET-O365DLCONFIGURATION
[8/11/2021 1:24:44 PM] - ********************************************************************************
[8/11/2021 1:24:44 PM] - GroupSMTPAddress = server
[8/11/2021 1:24:44 PM] - Using Exchange Online to capture the distribution group.
The current operation is not supported on GroupMailbox.
The current operation is not supported on GroupMailbox.
out-logfile : The current operation is not supported on GroupMailbox.
At C:\Program Files\WindowsPowerShell\Modules\DLConversionV2\2.2.0\DLConversionV2.psm1:2685 char:9
+         out-logfile -string $_ -isError:$TRUE
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Out-LogFile
```

**Comment by timmcmic** [comment]
Could you send me the full log.  ***@***.***)

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by derekhansell** [comment]
Your email address is being obfuscated in your replies. Maybe write it as _jim[at]microsoft[dot]com_ ?

**Comment by derekhansell** [comment]
Tim, thanks again for being so helpful.

I think I figured out the problem and it was user error (as usual). Apparently DirSync was set up to _include_ rather than exclude newly created OUs. So, even though I realized this mid-stream and excluded the OU from being synced, I think it screwed up the detection and proper deletion of the on-prem group.

I've successfully run the operations against two other groups now and it's gone fine.

One last question if you don't mind. I don't see anything in the blog posts about migrating many groups at once. Does running the evaluation steps first do that? Can I ingest a CSV of Groups I'd like to move? Etc?

**Comment by timmcmic** [comment]
Check out the multi-migration branch on git hub.

It's now multi threaded and coordinated.  I'm preparing a blog post and stress testing now.

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by derekhansell** [comment]
Awesome. I'd be moving about 100 groups. Is there built in telemetry or some other way I can collect data for you?

Cheers!

**Comment by timmcmic** [comment]
Let me get through this stress test first.

I should have it wrapped up by the end of the week.

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

**Comment by derekhansell** [comment]
@timmcmic

Hey there - another question: does this module handle nested DGs? Does it just migrate all the nested DGs at the same time, or...?

**Comment by derekhansell** [comment]
Oh, seems like you have to migrate the member DGs first. Trying that now. Do I have that right?

**Comment by timmcmic** [comment]
Correct - migrating with nesting is not assumed.  Top level DLs cannot be migrated until their sub DLs are migrated first.

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================
