### ISSUE TITLE
If Thread1 fails during a batch migration, all other threads stall for a long time

### ISSUE THREAD

**Issue by MassimoPascucci** [timmcmic/DLConversionV2#53]
During a batch migration, at most 5 threads are running concurrent migration; however, only the first one is responsible for triggering Active Directory replication and ADConnect synchronization. This is documented here: https://timmcmic.wordpress.com/2021/09/02/office-365-distribution-list-migrations-version-2-0-part-9.

If Thread1 fails end exits because of any error, all the other threads stall waiting for changes to appear in Azure AD, but no one is actually triggering an ADConnect sync. This should eventually resolve on its own, but depending on AD replication settings and ADConnect sync settings it might take quite a while.

**Comment by Massimo80** [comment]
Agreed.
