### ISSUE TITLE
Centralized Mail transport is always acknowledged

### ISSUE THREAD

**Issue by PeterNagl** [timmcmic/DLConversionV2#57]
I found that the warning about CMT that should trigger in **Test-OutboundConnector.ps1
** is always acknowledging the warning (and not halting the migration) even when no override is specified.

In the main function the var is initialized to $false if not set by the parameter:

`[boolean]$overrideCentralizedMailTransportEnabled=$FALSE,
[Parameter(Mandatory=$false)]`

the parameter goes directly to test-outboundConnector
`try {
        test-outboundConnector -overrideCentralizedMailTransportEnabled $overrideCentralizedMailTransportEnabled -errorAction STOP
    }
`

And in **Test-OutboundConnector.ps1** is a typo
Parameter is Centralized
if is looking for Central

`Param
        (
            [Parameter(Mandatory = $true)]
            $overrideCentral**ized**MailTransportEnabled
        )

        if ($overrideCentralMailTransportEnabled -eq $FALSE)
`

**Comment by timmcmic** [comment]
Ok I updated this in the refine ad calls branch if you want to test it.

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: Peter Nagl ***@***.***>
Sent: Monday, July 25, 2022 4:52 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Centralized Mail transport is always acknowledged (Issue #57)


I found that the warning about CMT that should trigger in **Test-OutboundConnector.ps1
** is always acknowledging the warning (and not halting the migration) even when no override is specified.

In the main function the var is initialized to $false if not set by the parameter:

[boolean]$overrideCentralizedMailTransportEnabled=$FALSE, [Parameter(Mandatory=$false)]

the parameter goes directly to test-outboundConnector
try { test-outboundConnector -overrideCentralizedMailTransportEnabled $overrideCentralizedMailTransportEnabled -errorAction STOP }

And in Test-OutboundConnector.ps1 is a typo
Parameter is Centralized
if is looking for Central

`Param
(
[Parameter(Mandatory = $true)]
$overrideCentralizedMailTransportEnabled
)

    if ($overrideCentralMailTransportEnabled -eq $FALSE)

`

-

**Comment by PeterNagl** [comment]
Fixed in your last build.
