### ISSUE TITLE
Start-MultipleDistributionListMigration fails with error Get-ConnectionContext 

### ISSUE THREAD

**Issue by NeilGordonCT** [timmcmic/DLConversionV2#62]
I can run Start-distributionListMigration without error however Start-MultipleDistributionListMigration fails 

\Documents\WindowsPowerShel
l\Modules\ExchangeOnlineManagement\2.0.6\netFramework\ExchangeOnlineManagement.ps
m1:531 char:38
+ ... onContext = Get-ConnectionContext -ExchangeEnvironmentName $ExchangeE ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ConnectionContext], Aggrega 
   teException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Exchange.Manag 
   ement.ExoPowershellSnapin.GetConnectionContext

command I'm running 

Start-MultipleDistributionListMigration -globalCatalogServer $gc -activeDirectoryCredential $cred -groupSMTPAddress $groupSMTP -logFolderPath $pathlog -dnNoSyncOU $NoSyncOU -exchangeOnlineCredential $cred

The command are both for Start-distributionListMigration and Start-MultipleDistributionListMigration

**Comment by timmcmic** [comment]
Please submit logs to dlconversionv2 @ service dot microsoft dot com

Tim

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: NeilGordonCT ***@***.***>
Sent: Tuesday, September 6, 2022 2:15 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Start-MultipleDistributionListMigration fails with error Get-ConnectionContext (Issue #62)


I can run Start-distributionListMigration without error however Start-MultipleDistributionListMigration fails

\Documents\WindowsPowerShel
l\Modules\ExchangeOnlineManagement\2.0.6\netFramework\ExchangeOnlineManagement.ps
m1:531 char:38

  *   ... onContext = Get-ConnectionContext -ExchangeEnvironmentName $ExchangeE ...

*                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*

     *   CategoryInfo : NotSpecified: (:) [Get-ConnectionContext], Aggrega
teException
     *   FullyQualifiedErrorId : System.AggregateException,Microsoft.Exchange.Manag
ement.ExoPowershellSnapin.GetConnectionContext

command I'm running

Start-MultipleDistributionListMigration -globalCatalogServer $gc -activeDirectoryCredential $cred -groupSMTPAddress $groupSMTP -logFolderPath $pathlog -dnNoSyncOU $NoSyncOU -exchangeOnlineCredential $cred

The command are both for Start-distributionListMigration and Start-MultipleDistributionListMigration

-

**Comment by timmcmic** [comment]
Account was utilizing MFA  - unfortunately due to non-interactive logon nature of the script the account cannot have MFA.

Secure the account with conditional access locations and bypass MFA <or> consider using cert auth / enterprise app.

**Comment by timmcmic** [comment]
Also version 2.0.6 of the exchange powershell module is not yet supported - the preview version does not have the commandlets necessary for full migrations to work.

==============================
Timothy J. McMichael
Senior Support Escalation Engineer
***@***.******@***.***>
(980)-776-7465

Hours:  Sunday - Wednesday 08:00 - 16:00 eastern time zone.

Manager:  Tom Roughley ***@***.******@***.***>)

Premier Support - (800)-936-3100
Broad Commercial Support - (800)-936-4900

==============================

From: NeilGordonCT ***@***.***>
Sent: Tuesday, September 6, 2022 2:15 PM
To: timmcmic/DLConversionV2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timmcmic/DLConversionV2] Start-MultipleDistributionListMigration fails with error Get-ConnectionContext (Issue #62)


I can run Start-distributionListMigration without error however Start-MultipleDistributionListMigration fails

\Documents\WindowsPowerShel
l\Modules\ExchangeOnlineManagement\2.0.6\netFramework\ExchangeOnlineManagement.ps
m1:531 char:38

  *   ... onContext = Get-ConnectionContext -ExchangeEnvironmentName $ExchangeE ...

*                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*

     *   CategoryInfo : NotSpecified: (:) [Get-ConnectionContext], Aggrega
teException
     *   FullyQualifiedErrorId : System.AggregateException,Microsoft.Exchange.Manag
ement.ExoPowershellSnapin.GetConnectionContext

command I'm running

Start-MultipleDistributionListMigration -globalCatalogServer $gc -activeDirectoryCredential $cred -groupSMTPAddress $groupSMTP -logFolderPath $pathlog -dnNoSyncOU $NoSyncOU -exchangeOnlineCredential $cred

The command are both for Start-distributionListMigration and Start-MultipleDistributionListMigration

-
